<%-- 
    Document   : fool
    Created on : 26 Oct, 2015, 3:37:40 PM
    Author     : gov
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <p><center><h3 class="h3class"><strong class="strongclass">पुष्प उत्पादन</strong></h3></center><br>
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;फूल अब केवल गृह वाटिका में  उगाने एवं पूजा में प्रयोग हेतु ही सीमित नहीं रह गए है परन्तु अब पुष्प उत्पादन एक व्यवसाय के रूप में काफी बढ़ रहा है। उपयोग के आधार पर फूलों को दो भागों में बाँटा गया है- प्रथम इस प्रकार के फूल जिनका प्रयोग पूजा-अर्चना एवं सामाजिक कार्यों में किया जाता है, जिनमें गेंदा, बेला, चमेली आदि फूल प्रमुख हैं। इन्हें खुले फूल भी कहा जाता है। <br>
  दूसरे प्रकार के वह फूल हैं जिनको कटे फूल के रूप में सजावट हेतु तथा निर्यात कर धन कमाने के लिए प्रयोग किया जाता है। इनमें प्रमुख फूल हैं- गुलाब, ग्लाइडियोलस्, झरबेरा, रजनीगंधा, कारनेशन, लिलियम, बल्र्ड आॅफ पैराडाइज, टुलिप, एन्थ्ूारियम, आरकिड इत्यादि। <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;सामान्य रूप से मध्यम वर्गीय किसानों एवं पुष्प उत्पादकों को प्रारम्भ में सलाह दी जाती है कि पहले गेंदा, रजनीगंधा, ग्लाइडियोलस, देशी गुलाब आदि फूल जिनको उगाने के लिए पाॅलीहाउस एवं अत्याधुनिक तकनीक की आवश्यकता कम होती है, उन्ही पुष्पों से पुष्प उत्पादन का कार्य प्रारम्भ करें तथा धीरे-धीरे बाजार की माँग के अनुसार पुष्प उत्पादन के कार्य को आगे बढ़ाया जाए। गेंदा, देशी गुलाब, ग्लाइडियोलस, रजनीगंधा, चाइना एस्टर आदि ऐसे फूल हैं जिनको आसानी से मैदानी क्षेत्रों मेें उगाया जा सकता है। कारनेशन, झरबेरा तथा गुलाब को ठण्डी जलवायु की आवश्यकता होती है, इसलिए इनको पहाड़ी क्षेत्रों में उगाया जा सकता है:
</p>
<p><strong class="strongclass">गेंदा</strong><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;गेंदे की खेती मैदानी क्षेत्रों में वर्ष भर तथा पहाड़ों पर अधिक ठण्डे मौसम को छोड़कर बाकी समय में की जा सकती है। गेंदे में दो प्रकार की किस्में पायी जाती हैं पहली- अफ्रीकन गेंदा, जिसका फूल बड़ा, रंग पीला, नारंगी तथा सफेद होता है। दूसरी प्रकार का गेंदा फ्रेंच है, जिसका पौधा छोटा, फूल का रंग लाल, पीला दोनों रंगो के मिश्रण लिए हुए होता है तथा फूल का आकार भी छोटा होता है।<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;गेंदे के बीज की बुवाई वर्ष में तीन बार की जाती है- प्रथम बार जून के मध्य में, रोपाई जुलाई के मध्य में तथा पुष्प उत्पादन बरसात के अन्त में होता है। दूसरी बार बीज की बुवाई सितम्बर के मध्य में, रोपाई अक्टूबर के मध्य में तथा पुष्प उत्पादन जाड़े में होता है। तीसरी बार बीज की बुवाई जनवरी-फरवरी माह में, रोपाई फरवरी-मार्च में तथा पुष्प उत्पादन गर्मी में होता है। एक हैक्टर क्षेत्रफल में रोपाई के लिए लगभग 3.0 कि.ग्रा. बीज की आवश्यकता होती है। बड़े आकार वाले गेंदे की रोपाई 45×60 वर्ग से.मी. की दूरी पर तथा छोटे आकार केे गेंदे की रोपाई 25×30 वर्ग से.मी. की दूरी पर करना उचित रहता है। रोपाई से पूर्व खेत में सड़ी हुई गोबर की खाद का प्रयोग 10-15 टन प्रति हैक्टर करना उचित रहता है। 100 कि.ग्रा. नत्रजन तथा फाॅस्फोरस एवं पोटाश की 200-200 कि.ग्रा. मात्रा अंतिम जुताई के समय मिट्टी में मिला देनी चाहिए। रोपाई के बाद 30 एवं 60 दिन के अन्तराल पर 50-50 कि.ग्रा. नत्रजन टापड्रेसिंग के रूप में प्रयोग करना उचित रहता है। खेत में हमेशा नमी बनाये रखें। जब पौधे 6 इंच के हो जायें तो एक बार मुख्य वृद्धि कलिका को तोड़़ दें इससे पौधे में शाखायें अधिक आयेंगी। जब शाखायें 6-6 इंच की हो जायें तो एक बार पुनः इनको तोड़ने से अधिक मात्रा में फूल प्राप्त होंगे तथा फूलों का आकार भी मध्यम होगा। भारत में दो किस्में पूसा द्वारा विकसित की गयी हैं - पूसा नारंगी एवं पूसा बसन्ती। दोनों ही अच्छी किस्में हैं। इसके अलावा स्पेश एज, अपोलो, मूनसोट, मेरीनार, एजटेक, अफ्रीकन किस्में हैं तथा टिना, सिगनेट, गोल्डन ब्वाॅय, बोनिटा, जिप्सी डान्सर आदि फ्रेन्च गेंदे की किस्में हैं। फूलों की पैदावार अफ्रीकन गेंदे से 8-12 टन प्रति हैक्टर तथा फ्रेन्च गेंदे से 11-18 टन प्रति हैक्टर तक प्राप्त की जा सकती है, यदि समय से रोपाई एवं उत्तम प्रबन्ध किये जायें तो और अधिक पैदावार की जा सकती है। </p>
<table class="MsoTableGrid" border="1" cellspacing="0" cellpadding="0" width="631" style="width:473.4pt;border-collapse:collapse;border:none;">
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">izeq[k jksx@dhV</span></strong></p></td>
    <td width="204" valign="top" style="width:153.0pt;border:solid black 1.0pt;border-left:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">y{k.k</span></strong></p></td>
    <td width="168" valign="top" style="width:126.0pt;border:solid black 1.0pt;border-left:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">fu;a=.k</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img src="./img/genda1.jpg" width="289" height="183" alt=""/><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="204" rowspan="2" valign="top" style="width:153.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g jksx eq[;r%    ikS/k&rdquo;kkyk esa yxrk gSA blds dkj.k ikS/kksa dk ruk Hkwfe lrg ij laØfer gksdj    fxjus yxrk gSA ;g <em>jktksDVksfu;k lksykuh</em> dod }kjk gksrk gSA </span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="168" rowspan="2" valign="top" style="width:126.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">blds fu;a=.k ds fy;s cht    dks cqokbZ ls iwoZ 2-0 xzke dSIVku izfr fd0xzk0 cht dh nj ls mipkfjr djuk    pkfg;sA ulZjh dh Hkwfe dk mipkj 2 izfr&rdquo;kr QkekZyhu ds ?kksy ls djuk pkfg;sA</span><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">vknzZ xyu</span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img src="./img/genda2.jpg" width="242" height="245" alt=""/><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="204" rowspan="2" valign="top" style="width:153.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g jksx <em>vYVjusfj;k    ldkZsLiksjk</em>  ,oa <em>lsIVksfj;k</em> dod }kjk QSyrk gSA <em>vYVjusfj;k VStksfVdk</em> rFkk <em>vYVjusfj;k U;wfl;k </em>dod xsank dh ifRr;ksa ij NksVs&amp;NksVs    gYds Hkwjs jax ds /kCcs ds :i esa fn[kkbZ nsrs gSa ftlls ikS/kk fprdcjk gks    tkrk gS rFkk ikS/ksa izdk&rdquo;k la&rdquo;ys&rsquo;k.k }kjk viuk Hkkstu ugha cuk ikrs gsSa    rFkk ikS/kk detksj gksdj ej tkrk gSA</span><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="168" rowspan="2" valign="top" style="width:126.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">bldh jksdFkke ds fy,    MkbFksu&amp;,e&amp;45 dod uk&rdquo;kh dk 0-2 izfr&rdquo;kr dh nj ls 15 fnu ds vUrjky ls    3&amp;4 ckj fNM+dko djuk pkfg;sA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">iRrh /kCck jksx </span></strong><strong><span style="font-family:'Times New Roman','serif'; font-size:14.0pt; ">(Leaf spot</span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">½</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img src="./img/genda3.jpg" width="225" height="216" alt=""/><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="204" rowspan="2" valign="top" style="width:153.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g chekjh ikS/k&rdquo;kkyk esa    c&lt;+rs gq;s ikS/kksa ij yxrh gSA bldk izdksi vf/kd ue Hkwfe esa vf/kd gksrk    gSA vkerkSj ij ;g cjlkr esa rFkk lnhZ ds izkjEHk esa gksrk gS rFkk fpduh o    Hkkjh feV~Vh esa vf/kd ns[kk x;k gSA </span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="168" rowspan="2" valign="top" style="width:126.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">bldk fu;a=.k djus ds fy,    laØfer ikS/kksa dks m[kkM+ dj [ksr ls ckgj tyk nsuk pkfg,A jksikbZ ls igys    Hkwfe dk &ldquo;kks/ku ,oa flapkbZ dks fu;af=r djds jksx ds izdksi de fd;k tk ldrk    gSA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">dkyj jkWV </span></strong><strong><span style="font-family:'Times New Roman','serif'; font-size:14.0pt; ">(Collor rot)</span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img src="./img/genda4.jpg" width="225" height="216" alt=""/><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="204" rowspan="2" valign="top" style="width:153.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g jksx dqdqEcj ekstsd    ok;jl }kjk QSyrk gSA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="168" rowspan="2" valign="top" style="width:126.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">bldh jksdFkke ds fy;s    jksxh ikS/kksa dks fudky dj lekIr dj nsuk pkfg;sA [ksr esa ,fQM rFkk yhQ    gkWij dk fu;a=.k eSykfFk;ku nok dk fNM+dko 0-2 izfr&rdquo;kr dh nj ls 7&amp;8 fnu    ds vUrjky ij djuk pkfg;sA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">fo&rsquo;kk.kq jksx</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img src="./img/genda5.jpg" width="244" height="240" alt=""/><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="204" rowspan="2" valign="top" style="width:153.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;s vYVjusfj;k MkbUFkh    dod }kjk QSyrk gSA blds y{k.k eq[; :i ls NksVh iq&rsquo;i dfydk ,oa iq&rsquo;i MaBy ij    gYds Hkwjs jax ds /kCcksa ds :i esa gksrh gS tks ckn esa cnydj xgjs Hkwjs jax    ;k dkys jax ds /kCcksa ds :i esa fn[kkbZ nsrh gSA iq&rsquo;i dfydk fldqM+dj lw[k    tkrh gSA blds y{k.k ifjiDo iq&rsquo;i dfydk ij de fn[kkbZ nsrs gSa ysfdu dfydk    f[kyus esa vlQy jgrh gSA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="168" rowspan="2" valign="top" style="width:126.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">blds fu;a=.k gsrq MkbFksu    ,e&amp;45 doduk&rdquo;kh dk fNM+dko 0-2 izfr&rdquo;kr dh nj ls ikuh esa ?kksy cukdj    10&amp;12 fnu ds vUrjky ij djuk pkfg;sA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">iq&rsquo;i dfydk ,oa    iq&rsquo;i foxyu</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img src="./img/genda6.jpg" width="205" height="236" alt=""/><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="204" rowspan="2" valign="top" style="width:153.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">Qwy vkus ds le; ;g dhV    fn[kk;h nsrk gSA bl dhV ds izdksi ls ikS/kk dqN /kwfey lk fn[kk;h nsrk gSA </span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="168" rowspan="2" valign="top" style="width:126.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">blds fu;a=.k ds fy,    dSYFksu uked dhVuk&rdquo;kh dh 2 fe-yh- ek=k izfr yhVj ikuh esa ?kksy cukdj fNM+dko    djuk pkfg,A</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">yky edM+h dhV</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img src="./img/genda7.jpg" width="188" height="150" alt=""/><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="204" valign="top" style="width:153.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g dhV xsans dh ifRr;ksa    dks [kkdj ikS/kksa dks {kfr igq¡pkrk gSA </span></p></td>
    <td width="168" valign="top" style="width:126.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;fn bl dhV dk izdksi    fn[kk;h ns rks 15 izfr&rdquo;kr esVsYMhgkbM uked dhVuk&rdquo;kh      /kwy dk iz;ksx dj bldk fu;a=.k fd;k tk    ldrk gSA</span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">Lyx</span></strong></p></td>
    <td width="204" valign="top" style="width:153.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">&nbsp;</span></p></td>
    <td width="168" valign="top" style="width:126.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">&nbsp;</span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img src="./img/genda8.jpg" width="242" height="244" alt=""/><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="204" rowspan="2" valign="top" style="width:153.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g loZ Hk{kh dhV gksrk gSA ;g ikS/ks dh dksey ifRr;ksa dks [kkrk gS    ftlls ikS/kksa dk Lo:i fcxM+ tkrk gS ,oa viuk iw.kZ Hkkstu ugha cuk ikrk gSA </span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="168" rowspan="2" valign="top" style="width:126.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">blds fu;a=.k ds fy, uqoku 50 bZ-lh- dk 1 fe-yh- izfr yhVj ikuh dh nj ls    fN+M+dko djuk pkfg;sA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">ckynkj lwM+h % </span></strong></p></td>
  </tr>
</table>


<p><strong class="strongclass">ग्लाईडियोलस</strong><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ग्लाईडियोलस के मध्यम आकार के बीमारी रहित कन्दों की छटाई कर उनको बेविस्टीन नामक दवा का घोल 2 ग्राम प्रति ली. पानी के हिसाब से बनाकर 30 मिनट तक डुबोकर रखा जाता है। तीस मिनट बाद कन्दों को निकालकर छाया में सुखाकर रोपाई के लिए तैयार किया जाता है। अधिक जैविक पदार्थ वाली हल्की भूमि ग्लाईडियोलस के लिए उत्तम रहती है। ग्लाइडियोलस के लिए भूमि तैयार करते समय ही 10 कि.ग्रा. गोबर की सड़ी खाद, 40 ग्राम नत्रजन, 20 ग्राम फास्फोरस एवं 20 ग्राम पोटाश प्रति वर्ग मीटर क्षेत्रफल के हिसाब से जमीन मे तैयारी करते समय ही मिला देना चाहिए। एक खेत में 2-3 वर्ष तक ही ग्लाईडियोलस की खेती करनी चाहिए, उसके बाद खेत को बदलते रहना चाहिए। मैदानी क्षेत्र में रोपाई 15 सितम्बर से प्रारम्भ कर एक-एक सप्ताह के अन्तराल पर करना उचित रहता है इससे पुष्प उत्पादन में भी निरन्तरता बनी रहती है। कन्द से कन्द की दूरी 15-20 सेे.मी. तथा लाइन से लाइन की दूरी 30 से.मी. रखते हुए रोपाई करनी चाहिए। पौधे अंकुरित होने पर हल्की मिट्टी चढ़ाना लाभप्रद रहता है। रोपाई के लगभग 75-90 दिन बाद फूल आने लगते हैं, प्रयोग के आधार पर फूलों (स्पाइक) को काटकर बिक्री हेतु बाजार में भेजा जाता है। यदि स्थानीय बाजार में फूलों की बिक्री की जानी है तो जब नीचे से 3-4 फूल पूरी तरह खिल जाये तभी फूलों को काटा जाना चाहिए। यदि फूलों को बाहर भेजना हो तो उन्हें तभी काटना चाहिए जब सबसे नीचे वाले फूल में हल्का रंग दिखने की अवस्था में हो, तत्पश्चात् फूलों को पानी में डालकर रखा जाना चाहिए। फूलों की आवश्यक छटाई के बाद आवश्यकतानुसार 10-10 या 20-20 के गुच्छों में बाँध कर गत्ते के डिब्बों में बन्द कर बाजार में भेज दिया जाता है। एक हैक्टर क्षेत्रफल में 80 हजार से एक लाख कन्दों की रोपाई की जाती है। इनसे इतने ही कन्द तथा फूल एवं 30-40 कुन्तल छोटे-छोटे कन्द (कार्मलेट) प्राप्त होते हैं जिन्हें एक ऋतु (सीजन) उगा कर पूर्ण कन्द के रूप में विकसित किया जा सकता है। ग्लाईडियोलस की उन्नत किस्में - अमेरिकन ब्यूटी, आस्कर, फ्रेन्डशिप, नजराना, आरती, अप्सरा, शोभा, सपना, अपोलो, अमेरिकन ब्यूटी, पूनम आदि हैं।<br>
</p>
<p><strong class="strongclass">रजनीगंधा</strong><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;रजनीगंधा में प्रमुख रूप से दो प्रकार की किस्में पायी जाती हैं- प्रथम वह किस्में हैं जिन पर सिंगल फूल आते हैं। इन किस्मों में खुशबू अधिक होती है तथा इनका प्रयोग तेल निकालने एवं गजरा तथा वेणी बनाने के लिए किया जाता है। द्वितीय प्रकार की वह किस्में हैं जिन पर डबल आकार के फूल आते हैं। इन किस्मों को कटे फूल के रूप में अधिक प्रयोग किया जाता है। तीसरी प्रकार की वह किस्में हैं जिन पर सिंगल फूल आते हैं परन्तु पत्तियां रंगीन होती है। इनमें रजत रेखा एवं स्वर्ण रेखा प्रमुख हैं। दो हाईब्रिड किस्में सुवासिनी एवं श्रंृगार अखिल भारतीय औद्यानिक अनुसंधान संस्थान, हसरगट्टा, बंगलौर द्वारा विकसित की गई हैं। इनका पुष्प उत्पादन अन्य किस्मों की तुलना में अधिक है।<br>
  रजनीगंधा की रोपाई हेतु उत्तर भारत के मैदानी क्षेत्रों में फरवरी-मार्च का समय सबसे उत्तम रहता है। रोपाई से पहले कन्दों को उपचारित कर कन्द से कन्द की दूरी 20-30 से.मी. तथा लाइन से लाइन की दूरी 20-30 से.मी. रखते हुए कन्द के आकार के अनुसार 4-7 से.मी. गहराई पर रोपाई की जाती है। एक हैक्टर क्षेत्रफल में 60 से 80 हजार तक कन्दों को रोपा जा सकता है तथा एक बार रोपाई करने के बाद उत्तम देखभाल करने पर तीन वर्ष तक अच्छा उत्पादन लिया जा सकता है। तीन वर्ष के बाद पुनः रोपाई करना उचित रहता है। रोपाई से पूर्व यदि खेत में 15-20 टन गोबर की सड़ी खाद प्रति हैक्टर के हिसाब से डाल दी जाये तो अच्छी फसल प्राप्त होती है। नत्रजन, फाॅसफोरस एवं पोटाश 200ः50ः70 कि.ग्रा. प्रति हैक्टर देना उचित रहता है। समय-समय पर निराई-गुड़ाई एवं अन्य कर्षण क्रियाऐं करते रहना चाहिए। एक बार कन्दों की रोपाई करने पर प्रति वर्ष लगभग 1-1.5 लाख पुष्प डन्डी एवं 35-60 कुन्तल तक कन्द प्राप्त होते हैं। जिनकी रोपाई तुरन्त की जा सकती है।<br>
</p>
<p>
    
<p align="center"><strong><span style="line-height:115%; font-family:'Kruti Dev 010'; font-size:17.0pt; ">jtuhxa/kk ds izeq[k dhV ,oa jksx</span></strong></p>
<table class="MsoTableGrid" border="1" cellspacing="0" cellpadding="0" width="625" style="border-collapse:collapse;border:none;">
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">izeq[k jksx</span></strong></p></td>
    <td width="180" valign="top" style="width:135.0pt;border:solid black 1.0pt;border-left:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">y{k.k</span></strong></p></td>
    <td width="186" valign="top" style="width:139.5pt;border:solid black 1.0pt;border-left:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">fu;a=.k</span></strong></p></td>
  </tr>
  <tr style="height:128.2pt;">
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:128.2pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><span style="font-family:'Times New Roman','serif'; "><img width="216" height="131" src="./img/Untitled-1_clip_image002.jpg" alt="Stem rot in tuberose"></span><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="180" rowspan="2" valign="top" style="width:135.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:128.2pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">bl jksx es ifRr;ksa ds    mij vFkok tehu ds ikl ekblhfy;k ds lkFk cu tkrh gSA ;g jksx <em>LdSysjksfl;e    jkyQlh lDd</em> uked dod }kjk mRiUu gksrk gSA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="186" rowspan="2" valign="top" style="width:139.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:128.2pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">bl jksx dh jksdFkke ds    fy, czklhdksy vFkok ftusc </span><span style="font-family:'Times New Roman','serif'; font-size:12.0pt; ">(20%)</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> 30 fdyksxzke izfr gSDV;j dh nj ls     fNM+dko djuk pkfg,A bl chekjh dks de djus ds fy;s e`nk ds ueh dks ueh    dks de djuk pkfg, vFkkok cYc dh jksikbZ vf/kd nwjh ij djuh pkfg,A</span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">ruk foxyu</span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
  </tr>
  <tr style="height:97.15pt;">
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:97.15pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><img width="231" height="124" src="./img/Untitled-1_clip_image004.jpg" alt="Flower bud rotting"></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="180" rowspan="2" valign="top" style="width:135.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:97.15pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g chekjh <em>bjohfu;k</em> Lih&rdquo;kht    }kjk gksrh gS</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> ftles iq&rsquo;idyh dkys Hkwjsa /kCcsa ij    dj lw[k tkrh gSA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="186" rowspan="2" valign="top" style="width:139.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:97.15pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">bldh jksdFkke ds fy,    jksx xzLr ikSa/kksa dks m[kkM+ dj u&rsquo;V dj nsuk pkfg,A bl chekjh ds jksdFkke ds    fy;s LVsªekbflu </span><span style="font-family:'Times New Roman','serif'; font-size:12.0pt; ">(0.01%)</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> dk iz;ksx djuk pkfg,A</span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">iq&rsquo;i dfydk lM+u    jksx</span></strong></p></td>
  </tr>
  <tr>
    <td width="625" colspan="3" valign="top" style="width:468.9pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">izeq[k dhV</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "><img width="244" height="167" src="./img/Untitled-1_clip_image006.jpg"></span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="180" rowspan="2" valign="top" style="width:135.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g gjs jax ds NksVs&amp;NksVs dhV &gt;q.M esa ubZ &ldquo;kk[kkvksa o Qwy dh    dyh ij ik;s tkrs gSa tks jl pwldj ikS/kksa dks gkfu igq¡pkrs gSaA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="186" rowspan="2" valign="top" style="width:139.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">ekgw rFkk fFkzIl dh    jksdFkke ds fy, jksxksj vFkok esVkflVkDl dks 1-75 ls 2-0 feyh0 izfr yh0 dh nj    ls ikuh esa ?kksy cukdj fNM+dko djuk pkfg,A</span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">ekgw vFkok isik</span></strong></p></td>
  </tr>
</table>
    
    
</p>


 <p> <strong class="strongclass">झरबेरा</strong><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;झरबेरा एक ऐसा फूल है जिसकी माँग स्थानीय बाजार के साथ-साथ विदेशी बाजार में भी काफी रहती है। गहरे रंग की डबल टाइप की किस्में जिनके फूल का केन्द्र काले रंग का हो, बाजार में अधिक प्रचलित है। झरबेरा को पाॅलीहाउस तथा शेडनेट हाउस के अन्दर उगाया जा सकता है। इसका प्रवर्धन टिशू कल्चर तकनीक एवं पुराने पौधों से सकर प्राप्त कर किया जाता है। रोपाई से पूर्व जमीन को उपचारित करना अत्यन्त आवश्यक है। जमीन को उपचारित करने के लिए फार्मलीन (फोरमल्डीहाइड) 100 मि.ली. को 5 ली. पानी में घोल कर प्रति वर्ग मी. क्षेत्रफल के हिसाब से जमीन को उपचारित कर पालीथीन सीट से ढक कर चारों ओर से मिट्टी से दबा दिया जाता है, जिससे गैस बाहर न निकल सके। लगभग 72 घण्टे बाद पालीथीन को हटाकर खेत की गुड़ाई कर उसे खुला छोड़ देते हैं। 1-2 दिन बाद उपचारित खेत की अच्छी तरह सिंचाई कर दी जाती है, जिससे बचा हुआ रसायनिक जमीन के नीचे चला जाए। इस प्रकार तैयार की गई जमीन में झरबेरा के पौधों की रोपाई क्राउन को ऊपर रखते हुए की जाती है। रोपाई का समय जनवरी से मार्च एवं जून से अगस्त अच्छा समय है। एक बार रोपाई करने के बाद 2-2.5 वर्ष तक अच्छे फूल प्राप्त किये जा सकते हैं। एक वर्ग मी. क्षेत्रफल में 6-7 पौधे लगाये जाते हैं। <br>
  उत्तम पुष्प उत्पादन हेतु झरबेरा में उचित मात्रा में उर्वरकों का प्रयोग अत्यन्त आवश्यक है। 10ः15ः20 ग्राम नत्रजन, फास्फोरस एवं पोटाश प्रति वर्ग मी. प्रति माह शुरू के तीन महीने व उसके बाद एन.पी.के. 15ः10ः30 की मात्रा में डालनी चाहिए।  इसके अलावा सूक्ष्म पोषक तत्वों का छिड़काव करना भी अच्छा रहता है। यदि फसल की अच्छी देख-रेख की जाए तो एक वर्ग मी. क्षेत्रफल से 130 से 160 फूल तक प्रथम ग्रेड के प्राप्त किये जा सकते हैं। यदि खुले क्षेत्र में उगा रहे हैं तो मात्र 12-20 प्रतिशत फूल ही प्रथम ग्रेड के प्राप्त होते हैं। झरबेरा की उन्नत किस्में इबिजा, गोल्ड स्पाॅंट, रोजाबेला, टोरान्डो आदि हैं।किये जाते हैं। इसके अतिरिक्त देशी किस्में, नूरजहाँ ग्रेस एन टेपलिस एवं रानी साहिबा आदि किस्मों के फूल तेल निकालने, गुलाब जल बनाने आदि व्यावसायिक कार्यों में प्रयोग होते हैं। देशी किस्मों के गुलाब के पौधों को कलमों द्वारा जाडे़ के मौसम में आसानी से बनाया जा सकता है, जबकि हाईब्रिड टी वर्ग के पौधे तैयार करने हेतु पहले देशी गुलाब की कलमें लगा कर उन पर उन्नत किस्मों की कलिका बाँध कर पौधे तैयार किये जाते हैं। यह कार्य मैदानी क्षेत्रों में अक्टूबर से फरवरी तक तथा पहाड़ी क्षेत्रों में फरवरी-मार्च माह में किया जाता है। देशी गुलाब को आसानी से खुले क्षेत्रों में उगाया जा सकता है, परन्तु हाईब्रिड गुलाब से उत्तम किस्म के फूल प्राप्त करने हेतु उन्हें पाॅलीहाउस में ही उगाना उचित होगा। हाईब्रिड गुलाबों में लाल, नारंगी एवं गुलाबी रंग के फूलों की बाजार में अधिक माँग रहती है। इसकी किस्में फस्र्ट रेड, सोनिया, ग्राण्ड गाला, विवल्डी, नोवलीज, कान्फेट्टी, वरसिल्लिया आदि हैं। गुलाब की रोपाई का सबसे अच्छा समय अक्टूबर माह है। पाॅलीहाउस में एक वर्ग मी. में 6 पौधों के हिसाब से रोपाई करना उत्तम रहता है। पाॅलीहाउस में जून से अगस्त तक पौधों को आराम में रखा जाता है। अर्थात् उनकी काट-छाॅंट कर उनमें खाद तथा उर्वरक देते हैं। खुले क्षेत्रों में यह कार्य अक्टूबर माह में किया जाता है। रोपाई के बाद हल्की सिंचाई करनी चाहिए। टपक (ड्रिप) विधि द्वारा सिंचाई करना उत्तम रहता है।<br>
  नत्रजन, फाॅस्फोरस एवं पोटाश के साथ-साथ मैग्नीशियम की उचित मात्रा का प्रयोग भी उत्तम रहता है। 6-8 कि.ग्रा. गोबर की सड़ी खाद, 40 ग्राम नत्रजन, 20 ग्राम फास्फोरस, 20 ग्राम पोटाश प्रति वर्ग मीटर के हिसाब से रोपाई से पहले गढ्ढ़ों में मिला दी जाती है। मैग्नीशियम का प्रयोग कमी के लक्षण दिखने पर किया जाता है। कीट तथा बीमारियों के नियंत्रण हेतु समय-समय पर उचित दवाओं का प्रयोग करते रहना चाहिए। फूलों की कटाई का सबसे अच्छा समय सुबह का होता है। यदि फूलों को दूर भेजना हो तो टाइट बड स्टेज पर अथवा फूल के आधा खिलने पर काटा जाता है। फूल को काटने के बाद कुछ समय तक ठण्डे तापमान पर रखते हैं, उसके बाद आवश्यक उपचार कर उसको 100 से.मी. लम्बे, 40 से.मी. चैड़े एवं 30 से.मी. गहरे गत्ते के डिब्बे में रखा जाता है तथा वातानुकूलित वाहन द्वारा उसे बाहर भेज दिया जाता है।<br>
  <br>
</p>

<p class="MsoNormal" style="text-align:center;"><strong><span style="line-height:115%; font-family:'Kruti Dev 010'; font-size:17.0pt; ">tjcsjk ds izeq[k dhV ,oa jksx</span></strong></p>
<table class="MsoTableGrid" border="1" cellspacing="0" cellpadding="0" width="625" style="border-collapse:collapse;border:none;">
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">izeq[k jksx@dhV</span></strong></p></td>
    <td width="192" valign="top" style="width:144.0pt;border:solid black 1.0pt;border-left:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">y{k.k</span></strong></p></td>
    <td width="174" valign="top" style="width:130.5pt;border:solid black 1.0pt;border-left:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">fu;a=.k</span></strong></p></td>
  </tr>
  <tr style="height:156.55pt;">
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:156.55pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img width="245" height="163" src="./img/jhabera1.jpg" alt="powdery mildew in gerbera"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="192" rowspan="2" valign="top" style="width:144.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:156.55pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g jksx ^<em>bjhlhdh    fludksfl,je</em>* ds dkj.k gksrk gSA blesa ifÙk;ksa ij lQsn ikmMj dh ijr lh cu    tkrh gS rFkk ckn esa ifÙk;k¡ ihyh iM+dj lw[k tkrh gSaA  </span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="174" rowspan="2" valign="top" style="width:130.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;height:156.55pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">izHkkfor ikS/kksa o    ifÙk;ksa dks u&rsquo;V dj nsuk pkfg,A ikS/kksa dks c¡wn&amp;c¡wn flapkbZ fof/k }kjk    flafpr fd;k tkuk pkfg, ftlls ikS/kksa dks vR;f/kd vknzZrk ls cpk;k tk ldsA Qsusjheksy    ¼0-5 feyh0 izfr yhVj½ ;k M;uksdsc ¼0-3 feyh0 izfr yhVj½ dk fNM+dko djuk    pkfg,A</span></p>
      <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">&nbsp;</span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">ikmMjh feYM~;w</span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><img width="207" height="132" src="./img/jhabera2.jpg" alt="Fusarium crown rot"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="192" rowspan="2" valign="top" style="width:144.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g chekjh feV~Vh dh lrg    ij rus ds fupys fgLls ij gksrh gSA dqN ikS/kks ds ifRr;ka ihyh iM tkrh gS    vkSj iwjk ikS/kk lw[k tkrk gSA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="174" rowspan="2" valign="top" style="width:130.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">feV~Vh dks esVkysDly ;k    doduk&rdquo;kh tSls dsIVku vkSj dkij vkDlhDyksjkbM ds ¼0-2 feyh0 xzk0 izfr yh0 ikuh    es½ ?kksy cukdj feV~Vh dks vPNh rjg ls rj dj nsuk pkfg,A </span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">dkyj jkWV</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "><img width="208" height="153" src="./img/jhabera3.jpg"></span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="192" rowspan="2" valign="top" style="width:144.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g jksx dks dbZ dodksa    }kjk tSls <em>ihfFk;e] LdysjksfV;e jksyfQlh</em>]    rFkk <em>jkbtksDVksfu;k lksysuh</em> }kjk    QSyrk gS tks tjcsjk ds tM rU= dks izHkkfor djrk gSA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="174" rowspan="2" valign="top" style="width:130.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">jksikbZ ds iwoZ feV~Vh    dks mipkfjr dj ysuk pkfg,A blds fy, dWkij vkDlhDyksjkbM dh 0-2 feyh0xzk0@yh0    ek=k }kjk bl jksx dks fu;f=r fd;k tkrk gSA</span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">tM lMu</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:15.0pt; "><img width="214" height="158" src="./img/jhabera4.jpg" alt="leaf miner in gerbera"></span><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="192" rowspan="2" valign="top" style="width:144.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g dhV ikS/kksa dh ifÙk;ksa ij vkM+h&amp;frjNh lqjaxsa cuk nsrs gSa]    ftldh otg ls ifÙk;k¡ gYdh ihyh ls Hkwjs jax dh gks tkrh gSA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="174" rowspan="2" valign="top" style="width:130.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:15.0pt; ">izHkkfor ikS/kksa dks u&rsquo;V dj nsuk pkfg,A lkbijesFkzhu    ¼0-5&amp;0-75 feyh0 izfr yhVj½ ;k MkbDyksoksl ¼0-5&amp;1-8 feyh0 izfr yhVj½    dks ikuh feykdj fNM+dko djsaA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
  </tr>
  <tr style="height:11.2pt;">
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:11.2pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">yhQ ekbuj</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "><img width="212" height="131" src="./img/jhabera5.jpg"></span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="192" rowspan="2" valign="top" style="width:144.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">gjs jax ds NksVs&amp;NksVs dhV &gt;q.M esa ubZ &ldquo;kk[kkvksa o Qwy dh dyh    ij ik;s tkrs gSa tks jl pwldj ikS/kksa dks gkfu igq¡pkrs gSaA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="174" rowspan="2" valign="top" style="width:130.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">essVkflLVkWDl ¼0-1%½    rFkk iSjkfFkvksu ¼0-02%½ dk fNM+dko djuk pkfg,A</span></p>
      <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">&nbsp;</span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">,fQM ¼ekgw½</span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "><img width="167" height="133" src="./img/jhabera6.jpg"></span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="192" rowspan="2" valign="top" style="width:144.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">;g NksVs&amp;NksVs Hkwjs    jax ds dhV gksrs gSa tks izk;% uaxh vk¡[kksa ls fn[kk;h ugha nsrs gSaA ;s    ifÙk;ksa dh fupyh lrg ij jgrs gSaA ifÙk;ksa dk jl pwldj /kCcs tSls cukrs gSaA    vf/kd ekbV yxus ij ifÙk;ksa ij tkyk cukrs gSA </span></p></td>
    <td width="174" rowspan="2" valign="top" style="width:130.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">b.MkslYQku ¼2-0    feyh0@yhVj½ ;k MbdksQky ¼1-5 feyh0 izfr yhVj½ dk fNM+dko blds fu;a=.k esa    lgk;d gksrk gSA</span></p>
      <p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; ">&nbsp;</span></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:15.0pt; ">ekbV~l</span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
  </tr>
  <tr>
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" align="center" style="margin-bottom:.0001pt;text-align:center;line-height:normal;"><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "><img width="228" height="157" src="./img/jhabera7.jpg"></span></strong><strong><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></strong></p></td>
    <td width="192" rowspan="2" valign="top" style="width:144.0pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:15.0pt; ">Hkwjs jax ds] ia[kksa okys phaVh dh rjg    fn[kus okyk vfr lw{e dhV gSA ;g dhV ikS/kksa dh eqyk;e &ldquo;kk[kk;sa] ifÙk;ksa]    Qwyksa dh dyh dk jl pwlrs gSa] ftlls eVeSys Hkwjs jax ds /kCcs iM+ tkrs gSaA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
    <td width="174" rowspan="2" valign="top" style="width:130.5pt;border-top:none;border-left:none;border-bottom:solid black 1.0pt;border-right:solid black 1.0pt;padding:0cm 5.4pt 0cm 5.4pt;"><p class="MsoNormal" style="margin-bottom:.0001pt;text-align:justify;line-height:normal;"><span style="font-family:'Kruti Dev 010'; font-size:15.0pt; ">b.MkslYQku ¼2-0 feyh0@yhVj½ ;k MkbdksQky    ¼2-0 feyh0 izfr yhVj ikuh esa ?kksydj fNM+dko dj fFkzIl ij fu;a=.k dj ldrs    gSaA</span><span style="font-family:'Kruti Dev 010'; font-size:14.0pt; "> </span></p></td>
  </tr>
  <tr style="height:15.7pt;">
    <td width="259" valign="top" style="width:194.4pt;border:solid black 1.0pt;border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:15.7pt;"><p class="MsoNormal" align="center" style="margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;text-align:center;text-indent:-36.0pt;line-height:150%;"><strong><span style="line-height:150%; font-family:'Kruti Dev 010'; font-size:15.0pt; ">fFkzIl</span></strong><span style="font-family:'Kruti Dev 010'; font-size:15.0pt; "> </span></p></td>
  </tr>
</table>


<p><strong class="strongclass">लिलियम</strong><br>
  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;लिलियम की खेती के लिए मृदु जलवायु की आवश्यकता होती है। इसको जाली एवं प्लास्टिक घरो मंे उगाया जाता है। जहां पर इसकी खेती के लिए उचित जलवायु हो वहां इसकी खेती खुले क्षेत्रों में की जा सकती है। खुले क्षेत्रों के खेती करने से तेज हवा आंधी, कुहरा तथा रोगों आदि से हानि होने का खतरा बना रहता है। कम प्रकाश की तीव्रता मे लिलियम के वृद्धि अच्छी होती है। लिलियम में जड़ तन्त्र के विकास के समय 12-13 डिग्री से.ग्रे. के तापमान की आवश्यकता होती है। इसकी दो प्रकार की प्रजातियां प्रमुख हैं। एशियाटिक और ओरिएंटल लिलियम।<br>
  रोपाई से पहले गोबर की सड़ी खाद या कम्पोस्ट 6 कि.ग्रा. प्रति वर्ग मी. नारियल का बुरादा 6 कि.ग्रा. प्रति वर्ग मी. कैल्शियम अमोनियम नाइट्रेट खाद 50 ग्राम प्रति वर्ग मी., डी.ए.पी. 30 ग्राम प्रति वर्ग मी. व म्यूरेट आॅफ पोटाश 30 ग्राम प्रति वर्ग मी. क्षेत्र के हिसाब से मिट्टी में मिलाए। लिलियम को मुख्यतः वानस्पतिक प्रवर्धन के द्वारा और कभी-कभी बीज से भी प्रवर्धन किया जाता है। वानस्पतिक प्रवर्धन विभाजन या कन्द द्वारा करते हैं। ऊतक संवर्धन विधि द्वारा भी इसके      पौधे तैयार किये जाते हैं।<br>
  मैदानी क्षेत्रों के लिए इसकी बुवाई का समय अक्टूबर-नवम्बर माह के बीच व पहाड़ी क्षेत्रों के लिए अप्रैल-मई के बीच है। लिलियम में फूल मैदानी क्षेत्रों में जनवरी-फरवरी तथा पहाड़ी क्षेत्रों में जुलाई-अगस्त में आते है। कन्द से कन्द की दूरी 15 से.मी. व कतार से कतार की दूरी 25 से.मी. रखी जाती है। रोपाई के समय कन्दों को 15 से.मी. की गहराई पर बोया जाता है।<br>
  खाद एवं उर्वरक नियंत्रण बुवाई के तीन सप्ताह पश्चात् 100 ग्राम यूरिया, 60 ग्राम म्यूरेट आॅफ पोटाश प्रति 10 वर्ग मी. के हिसाब से क्यारियों में मिलाए। यह कार्य पुनः दस दिन के अंतराल पर किया जाना चाहिए। नाइट्रोजन उर्वरक को मिलाने के पश्चात् पौधों की अच्छी तरह से सिंचाई करें ताकि पत्तियों को झुलसने से बचाया जा सके। ड्रिप सिंचाई को लिलियम के लिए उत्तम माना जाता है। रोपण से पहले खरपतवारों को खेत से निकाल दें तथा भूमि को उपचारित कर लेना चाहिए। खरपतवार को उथली खेती, मल्चिंग, खरपतवारनाशक रसायन से खरपतवारों को आसानी से निंयन्त्रित किया जा सकता है।<br>
  पुष्पवृन्तों को उस समय काटना चाहिए जब निचली कली अपना रंग दिखाने लगे या आधी खुल जाये। पुष्पवृन्तों को सामान्यतः सुबह के समय काटना चाहिए। पुष्प डंडी को जमीन के नजदीक से काटें पुष्प डंडियों को खीचकर नहीं निकालना चाहिए। फूलों का गुलदान अवधि, किस्म, मौसम और फूलों के रख-रखाव के तापमान पर निर्भर करती है। लिलियम के पुष्पों को उचित संरक्षक में 2-3 सेन्टीग्रेट तापमान पर 10 मिनट तक रखना चाहिए ताकि खेत ऊष्मा को कम किया जा सकें। ताजे कटे पुष्पों को पुष्परक्षक घोल में रखकर उनको काफी समय तक ताजा बनाए रखने के लिए प्रयोग किया जाता है। पुष्परक्षक घोल का प्रयोग पुष्प कली खुलने व गुलदान अवधि बढाने में सहायक होते हैं। ताजे कटे हुए लिलियम के फूलों को शर्करा एवं सिल्वर थायोसल्फेट (20 पी.पी.एम.) के घोल मे 2.0 डिग्री से.ग्रे. तापमान पर दो घण्टे के लिए कमरे में रखना चाहिए।<br>
  लिलियम के ताजे पुष्पों को शुष्क अवस्था में पाॅलिथीन की फाॅयल में 1-5 से.ग्रे. तापमान पर 4-6 हफ्तो के लिए भण्डारित किया जा सकता है। पुष्पों को लपेटने से पहले नीचे की एक तिहाई पत्तों को हटा देना चाहिए। गर्मियों में 2-3 महीनों के लिए कन्दों एवं घनकन्दों का भण्डारण हवादार प्लास्टिक की टेª में पीट माॅस या बुरादे के साथ  2-3 सेन्टीग्रेट तापमान व 70 प्रतिशत आर्द्रता में करना चाहिए।<br>
  फूलांे की ग्रेडिंग पुष्प कलियां प्रति डंडी, डंडी की लम्बाई, परिपक्वता व स्थिरता पर निर्भर करती है। पुष्प डंडियों की लम्बाई में 5 प्रतिशत से ज्यादा का अन्तर नहीं होना चाहिए। एक पुष्प डंडी में कम से कम पाँच कलियां होना आवश्यक है। 4-5 डंडियों का एक गुच्छा बनाया जाता है। हर एक बंच में कम से कम 20 कलियां होती है। पैकिंग से पूर्व नीचे से 10 से.मी. तक की पत्तियों को हटा दिया जाता है। इसके पश्चात् पुष्प डंडियों को नीचे से बांध कर प्लास्टिक थैलियों से ढक दिया जाता है। लिलियम को प्रशीतक वाहनों में (2-3 डिग्री       से.ग्रे.) भेजा जाना चाहिए। लिलियम के उपज कन्द के आकार तथा पौधे की दूरी पर निर्भर करती है। समय के अनुसार प्रति पुष्प डंडी का मूल्य 15-50 रू. तक प्राप्त होता है।<br>
  </p>
  <p><strong class="strongclass">गुलदाउदी</strong><br>
  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;गुलदाउदी एक बहुमुखी फूल है, इसे क्यारियों में, गमलों में उगाया जा सकता है। इसका उपयोग माला बनाने में एवं कर्तिक फूलों के रूप में पुष्प सज्जा में किया जाता है। भारत में बडे फूलों के आकार वाली प्रजातियों का भीतरी सजावट के लिए कर्तिक फूलों के रूप में एवं प्रदर्शनी के लिए उगाया जाता है। जबकि छोटे आकार वाली प्रजातियों को कर्तित फूल, मालाए गजरा, वेणी, पूजा, और गमलों एवं क्यारियों के उद्देश्य से उगाया जाता है।<br>
  यह एक रेशेदार जड़ विन्यास वाला पौधा है जो कि खराब जल निकास से बहुत प्रभावित होता है।<br>
  क्यारियों में पौधे लगाने से पहले भूमि की 2-3 बार अच्छी प्रकार से जुताई की जाती है। अखिल भारतीय समन्वित पुष्प विज्ञान परियोजना द्वारा 5 कि.ग्रा. प्रति वर्ग मी. गोबर की खाद का उपयोग उचित पाया गया है। गुलदाउदी का प्रवर्द्धन वानस्पतिक तरीके से जैसे-सकर्स, कलम एवं ऊतक विधि द्वारा किया जाता है।<br>
गुलदाउदी की प्रमुख किस्में कीर्ति, अर्का स्वर्णा, बीरबल साहनी, शान्ति, वाई टू के, अर्का गंगा, सदभावना, अप्पू, बिंदिया, कोयम्बटूर-1 पंकज, इत्यादि हैं।<br>
अच्छे किस्मों के पौधों से तैयार ऊपरी भाग की कलमों से जून माह में तैयार किया जाता है और उन्हें जड़ निकलने के पश्चात् 15 से.मी. गहराई वाले गमले के या तैयार क्यारियों के जून माह के अन्त में रोपित किया जाता है। यह पौधे जुलाई माह के अन्त एवं सितम्बर के आरम्भ में पिचिंग के लिए तैयार हो जाते है। 30ग 30 से.मी. (पौधा से पौधा तथा लाइन से लाइन) दूरी रखते हुए रोपाई की जाती है।<br>
उचित मात्रा में खाद एव उर्वरक का उपयोग करने से फसल अच्छी होती है। 8-10 टन गोबर की खाद प्रति एकड़, 50 कि.ग्रा. नाइट्रोजन, 160 कि.ग्रा. फाॅस्फोरस और 80 कि.ग्रा. पोटाश प्रति एकड़ की दर से मृदा में मिला देनी चाहिए।<br>
सिंचाई की आवृति वृद्धि के स्तर मृदा एवं मौसम की दशा पर निर्भर करती है। क्यारियों एवं गमलों में रोपित गुलदाउदी के लिए उचित व्यवस्था होनी चाहिए। गुलदाउदी के पौधे की उचित वृद्धि एवं विकास सिंचाई की मात्रा एवं आवृति पर निर्भर करती है।<br>
रोपाई के 3-4 माह पश्चात् गुलदाउदी की फसल में फूल आने प्रारम्भ हो जाते है जो कि गुलदाउदी की प्रजातियों पर निर्भर करते हैं। कर्तित फूलों हेतु तने को मृदा से 10 से.मी. उपर तक काट देते हैं। फूलों की उम्र को बढाने के लिए तने का 1ध्3 हिस्सा पानी में डुबों देते हैं। फूलों को सुरक्षित रखने के लिए उन्हें प्लास्टिक की थैलियों में रखना चाहिए। फूलों की कटाई का समय प्रजाति, विपणन एवं उद्ेदश्य पर निर्भर करता है।<br>
फूलों का वर्गीकरण (ग्रेडिंग) तने की लम्बाई, फूल के रंग एवं फूल के व्यास के आधार पर किया जाता है। परिपक्व फूलों को पाॅलीथीन में लपेट कर 6-8 हफ्तों के लिए 0.50 सें.गे्र. तापमान पर सूखे स्थान पर रख सकते हैं। शिथिल फूलों के विपणन के लिए बाॅस से बनी टोकरियों या जूट के थैलों में पैक करना चाहिए। एक टोकरी की क्षमता 1-7 कि.ग्रा. जबकि जूट के थैले में 30 कि.ग्रा. शिथिल फूल रखे जा सकते हैं।<br>
रोपाई के पश्चात् पौधे में मुख्यतः उपर की ओर वृद्धि होती है। जबकि शाखायें कम मात्रा में होती है। पौधे की लम्बाई को रोकने के लिए एक साधारण प्रक्रिया जिसे पिन्चिंग कहते हैं उपयोग में लायी जाती है। यह प्रकिया मुख्यतः बडे़ व आकर्षक फूलों के उत्पादन के लिए की जाती है। स्प्रे प्रजातियों में डिसबडि़गं प्रक्रिया अत्यन्त सरल होती है क्योंकि इनमें केवल बड़ी शीर्षस्थ कलिकाओं को तोड़कर अलग कर देते हैं और तटस्थ कलिकाओं को पनपने देते हैं जबकि स्टैडर्ड प्रजातियों में शीर्षस्थ कलिकाओं को उगने देते हैं और तटस्थ कलिकाओं केा तोड़ देते हैं।<br>
पौधे को सीधा रखने के लिए सहारे की आवश्यकता होती है तथा उचित आकार एवं फूलों के खिलने के लिए भी सहारे की आवश्यकता होती है। सहारे के लिए बाॅस की डण्डियों का उपयोग करते हैं। पौधों में सहारे की आवश्यकता उसे सीधा रखने के लिए होती है। <br>
गुलदाउदी के फूलों का कटे फूलों के अलावा लूज़ फूलांे, माला, गुलदस्ता, ग्रीटिंग कार्ड एवं सूखे फूलों के रूप में इस्तेमाल किया जाता है।<br>
गुलदाउदी फसल उगाने में 9000-15000/एकड़ का खर्च आता है एवं रू. 25,000-50,000/एकड़ का शुद्ध मुनाफा (औसतन) होता है जो कि मौसम, स्थान एवं विपणन पर निर्भर करता है।<br>
</p>
<p><strong class="strongclass">कमल</strong><br>
</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;कमल, भारत का राष्ट्रीय पुष्प है। कमल एक बहुवर्षीय जलीय पौधा है जो अपनी सुन्दरता एवं कोमलता के कारण सौंदर्य, वैभव एवं उर्वरता का प्रतीक है। प्राकृतिक रूप से कमल की बागवानी धीरे बहाव वाले या स्थाई पानी में, उष्ण या उपोष्ण जलवायु वाले स्थानों पर एवं समुद्र तल से 1800 मीटर की ऊँचाई वाले स्थानांे पर आसानी से की जा सकती है। <br>
  यह एक ऊष्ण कटिबंधीय जलवायु में एवं गहरे पानी में पनपने वाला जलीय पौधा है। इस पुष्प की वृद्धि के लिए 20-30 डिग्री से.ग्रे. तापमान तथा खुली धूप की आवश्यकता होती है। वृद्धि के दौरान पानी का तापमान 18 डिग्री से.ग्रे. से कम नहीं होना चाहिए। अधिक ठण्ड में यह पौधा प्रसुप्तावस्था में चला जाता है तथा अत्यधिक ठंडे तापमान में यह नष्ट भी हो जाता है।<br>
  कमल की प्रमुख किस्मंे नीलम्बो न्यूसीफेरा, नीलम्बो ल्यूटिया, एम्बोलीन, अलैक्जैन्डर द ग्रेट, बिग बेन, बोनी क्लाइडे हैं। कमल का प्रवर्धन प्रकंदों, बीजों एवं पौधे के विभाजन द्वारा किया जाता है।<br>
  पुष्प एवं प्रकंद उत्पादन तथा भू-सौन्दर्यीकरण हेतु वर्तमान समय में कमल को कृत्रिम, कंकरीट एवं फाइबर ग्लास के तालाबों में भी रोपित किया जा रहा है। प्रकंदों की अधिक उपज के लिये तालाब में उगाते हैं। कमल की रोपाई मार्च-अप्रैल में करनी चाहिए। चूँकि यह ग्रीष्म ऋतु की फसल है, अतः अधिकतम पुष्प उत्पादन बरसात में होता है। प्रकंदों के रोपण के 4-5 माह बाद पुष्प खिलने प्रारंभ हो जाते हैं, जबकि बीज द्वारा प्रवर्धन से यह 6-7 महीने में पुष्प देता है या कभी-कभी पुष्पन, रोपण के एक वर्ष के बाद भी नहीं होता है। प्रकंदों को 45     कि.ग्रा. प्रति हैक्टर तथा बीज को 10 कि.ग्रा. प्रति हैक्टर की दर से लगाना चाहिए।<br>
  कम पानी की स्थिति में तालाब में पौधों का रोपण सीधे मिट्टी में कर देना चाहिए। सर्दियों में कम पानी जल्दी गरम हो जाता है एवं यह पुष्पों के उत्पादन में सहायक होता है। प्रकंदों के रोपण के लिए तालाब में 25-30 सें.मी. मोटाई तक मिट्टी भरी जाती है। प्रकंदों को क्षैतिज दिशा में 300 के कोण पर लगाया जाता है। प्रकंदों को ढक दिया जाता है तथा केवल शीर्ष कलिका को ऊपर खोल दिया जाता है। इसके पश्चात् 10 सें.मी. स्तर तक पानी भर देते हैं, जिससे शीर्ष कलिका पानी से ढक जाए। जब पौधों में 5-6 पत्तियाँ आ जाएं तो प्रकंदों पर मिट्टी चढ़ा देनी चाहिए एवं जल का स्तर 30 सें.मी. कर देना चाहिए। इससे पुष्पन शीघ्र हो जाता है। यह क्रिया दोहराते रहने से अच्छी गुणवत्तायुक्त पुष्पों का उत्पादन होता है।<br>
  तालाब की सुन्दरता को बनाए रखने के लिए पौधों की उचित देखरेख आवश्यक होती है। मच्छर से बचाव के लिये तालाब में रंगबिरंगी मछलियाँ डाल देनी चाहिए। इससे तालाब की शोभा बढ़ जाती है। <br>
  कमल के पुष्पों का रोपण गमलों या पात्रों में भी किया जाता है। गमलों में बीजों की बुवाई तालाब में की गई बुवाई जैसी ही होती है। कमल के पौधों की जड़ चैड़ाई में फैलती है, अतः इनका रोपण गोल एवं चैड़े गमलों में किया जाता है। चैकोर गमलों में जड़ों के नष्ट होने की आशंका अधिक रहती है। कमल के पुष्पों को उत्पन्न करने के लिये कम से कम 45-60 सें.मी. व्यास तथा 25-30 सें.मी. गहराई वाले गमलों का प्रयोग करना चाहिए। कमल की बौनी किस्मों को छोटे गमलों में भी उगाया जा सकता है। कमल की अलग-अलग किस्मों को अलग-अलग गढ़ों में लगाना अधिक लाभ प्रद रहता है।<br>
  मृदा में पर्याप्त मात्रा में गोबर की सड़ी हुई खाद मिली होनी चाहिए। इससे पुष्पों की गुणवत्ता एवं उपज में वृद्धि होती है। इसके साथ में उपरोक्त मृदा मिश्रण का ही प्रयोग करना चाहिए। उर्वरक के रूप में धीमी गति से उर्वरक प्रदान करने वाली 6 गोलियों को रोपाई से पहले पात्रों की तली में डाल देते हैं। उत्तम वृद्धि एवं पुष्पन के लिए इनको 1 महीने के अंतराल पर प्रयोग करना चाहिए। हड्डियों का चूर्ण 125 ग्राम प्रति वर्ग मीटर की दर से उपयोग करने पर इसके पुष्पों का रंग चटक हो जाता है। उर्वरक की गोलियों को डालते समय सावधानी रखनी चाहिए।<br>
  सुदूर स्थानों पर परिवहन हेतु बड़ी कलियों, को पाॅलीथीन के थैलों में अथवा बांस की टोकरियों में कपड़े में लपेटकर संवेष्ठित किया जाता है। इन कलियों की मात्र आयु 3-4 दिन तक होती है। प्रकंदों की आयु 2 सप्ताह तक होती है। अतः इन्हें सुखाकर, जमाकर या पकाकर टिन के डिब्बों में बन्द कर दूर के स्थानों पर भेजा जाता है। प्रकंदों को उनकी मिट्टी में भी भण्डारित किया जा सकता है। इनको रोपण से पूर्व ठण्ड में जमने से बचाने के लिये मिट्टी के ऊपर 15-20 संे.मी. पानी भरकर तथा 5-10 डिग्री से.ग्रे. तापमान बनाए रखना चाहिए।<br>
  भारत में प्रकंदों की उपज 3.8-4.7 टन प्रति हैक्टर पाई गई है, जबकि मलेशिया में 3.1-8.2 टन प्रति हैक्टर तथा जापान में प्रकंदों की उपज 13.7 टन प्रति हैक्टर तक होती है। सामान्यतः प्रति वर्ष एक पौधे से 2-5 पुष्प प्राप्त किये जा सकते हैं।
</p>
    </body>
</html>
